# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6b08501869cd542a1d203c895f051c78"
name = "wishlist-inc"
handle = "wishlist-inc"
application_url = "https://cigarettes-refers-rendered-ugly.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "getdevdone.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://cigarettes-refers-rendered-ugly.trycloudflare.com/auth/callback",
  "https://cigarettes-refers-rendered-ugly.trycloudflare.com/auth/shopify/callback",
  "https://cigarettes-refers-rendered-ugly.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
